In [14]:
import pandas as pd

mises_citations_df = pd.read_csv("../data/processed/mises_citations.csv")
hayek_citations_df = pd.read_csv("../data/processed/hayek_citations.csv")
citations_df = pd.read_csv("../data/processed/citations.csv")

In [15]:
hayek_citations_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6281 entries, 0 to 6280
Data columns (total 21 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Unnamed: 0            6281 non-null   int64
 1   paper_id              6281 non-null   int64
 2   raw                   6281 non-null   object
 3   context               6281 non-null   object
 4   co_cited_count        6281 non-null   int64
 5   section_id            6133 non-null   object
 6   paragraph_id          6281 non-null   object
 7   sentence_id           6281 non-null   object
 8   sentence_seq_number   6281 non-null   int64
 9   reference_seq_number  6281 non-null   int64
 10  author                6281 non-null   object
 11  page                  3124 non-null   float64
 12  year                  5768 non-null   float64
 13  title                 6281 non-null   object
 14  filename              6281 non-null   object
 15  sentence_count        6281 non-null   int64
 16  reference_count       6281 non-null   int64
 17  source title          5882 non-null   object
 18  similarity            6281 non-null   float64
 19  keywords              6281 non-null   object
 20  book                  6281 non-null   object
dtypes: float64(3), int64(7), object(11)
memory usage: 1.0+ MB

In [16]:
import pandas as pd

def build_table(mises_df, hayek_df, citations_df, unit_col):
    
    # Conjuntos principais
    mises_set = set(mises_df[unit_col].dropna().unique())
    hayek_set = set(hayek_df[unit_col].dropna().unique())
    
    full_set = set(citations_df[unit_col].dropna().unique())
    
    # Outros autores (exclui Mises e Hayek)
    others_df = citations_df[
        ~citations_df['author'].isin(['Mises', 'Hayek'])
    ]
    others_set = set(others_df[unit_col].dropna().unique())
    
    # Complementos
    not_mises = full_set - mises_set
    not_hayek = full_set - hayek_set
    
    # Função auxiliar segura
    def safe_div(num, den):
        return num / den if den > 0 else 0
    
    # Probabilidades condicionais
    results = {
        'P(Hayek | Mises)': safe_div(len(mises_set & hayek_set), len(mises_set)),
        'P(Mises | Hayek)': safe_div(len(mises_set & hayek_set), len(hayek_set)),
        
        'P(Outros | Mises)': safe_div(len(mises_set & others_set), len(mises_set)),
        'P(Outros | Hayek)': safe_div(len(hayek_set & others_set), len(hayek_set)),
        
        'P(Mises | Outros)': safe_div(len(mises_set & others_set), len(others_set)),
        'P(Hayek | Outros)': safe_div(len(hayek_set & others_set), len(others_set)),
        
        'P(Hayek | ¬Mises)': safe_div(len(hayek_set & not_mises), len(not_mises)),
        'P(Mises | ¬Hayek)': safe_div(len(mises_set & not_hayek), len(not_hayek)),
        
        'P(Outros | ¬Mises)': safe_div(len(others_set & not_mises), len(not_mises)),
        'P(Outros | ¬Hayek)': safe_div(len(others_set & not_hayek), len(not_hayek)),
    }
    
    table = pd.DataFrame({
        'Probabilidade': list(results.keys()),
        'Valor': list(results.values())
    })
    
    # 🔥 Ordena da maior para a menor
    table = table.sort_values(by='Valor', ascending=False).reset_index(drop=True)
    
    return table

In [17]:
sentence_table = build_table(
    mises_citations_df,
    hayek_citations_df,
    citations_df,
    'sentence_id'
)

print('Sentence-level probabilities')
sentence_table

Sentence-level probabilities

        Probabilidade     Valor
0  P(Outros | ¬Mises)  0.976515
1  P(Outros | ¬Hayek)  0.970488
2   P(Outros | Hayek)  0.263824
3   P(Outros | Mises)  0.253837
4    P(Mises | Hayek)  0.095833
5    P(Hayek | Mises)  0.077529
6   P(Mises | ¬Hayek)  0.038051
7   P(Hayek | ¬Mises)  0.030412
8   P(Mises | Outros)  0.010692
9   P(Hayek | Outros)  0.008990

In [18]:
paragraph_table = build_table(
    mises_citations_df,
    hayek_citations_df,
    citations_df,
    'paragraph_id'
)

print('Paragraph-level probabilities')
paragraph_table

Paragraph-level probabilities

        Probabilidade     Valor
0  P(Outros | ¬Mises)  0.982882
1  P(Outros | ¬Hayek)  0.977834
2   P(Outros | Hayek)  0.643593
3   P(Outros | Mises)  0.630948
4    P(Mises | Hayek)  0.193449
5    P(Hayek | Mises)  0.156240
6   P(Mises | ¬Hayek)  0.054670
7   P(Hayek | ¬Mises)  0.042740
8   P(Mises | Outros)  0.040416
9   P(Hayek | Outros)  0.033296

In [19]:
section_table = build_table(
    mises_citations_df,
    hayek_citations_df,
    citations_df,
    'section_id'
)

print('Section-level probabilities')
section_table

Section-level probabilities

        Probabilidade     Valor
0  P(Outros | ¬Mises)  0.995442
1  P(Outros | ¬Hayek)  0.993387
2   P(Outros | Hayek)  0.956155
3   P(Outros | Mises)  0.949568
4    P(Mises | Hayek)  0.442496
5    P(Hayek | Mises)  0.365561
6   P(Mises | Outros)  0.130480
7   P(Hayek | Outros)  0.108542
8   P(Mises | ¬Hayek)  0.097146
9   P(Hayek | ¬Mises)  0.072452

In [20]:
paper_table = build_table(
    mises_citations_df,
    hayek_citations_df,
    citations_df,
    'paper_id'
)

print('Paper-level probabilities')
paper_table

Paper-level probabilities

        Probabilidade     Valor
0   P(Outros | Mises)  1.000000
1   P(Outros | Hayek)  1.000000
2  P(Outros | ¬Mises)  1.000000
3  P(Outros | ¬Hayek)  1.000000
4    P(Mises | Hayek)  0.874903
5   P(Mises | Outros)  0.696557
6    P(Hayek | Mises)  0.615426
7   P(Mises | ¬Hayek)  0.525223
8   P(Hayek | Outros)  0.489974
9   P(Hayek | ¬Mises)  0.201995

Análise de Keywords

In [29]:
import pandas as pd
import numpy as np

def prepare_keywords(df, author_name):
    df = df.copy()
    
    # converter keywords para lista
    if isinstance(df["keywords"].iloc[0], str):
        df["keywords"] = df["keywords"].str.split(",")
    
    df["keywords"] = df["keywords"].apply(
        lambda lst: [k.strip() for k in lst] if isinstance(lst, list) else []
    )
    
    df = df.explode("keywords")
    df["author"] = author_name
    
    return df[["sentence_id", "keywords", "author"]]

# --- Preparação ---
mises = prepare_keywords(mises_citations_df, "Mises")
hayek = prepare_keywords(hayek_citations_df, "Hayek")

df = pd.concat([mises, hayek], ignore_index=True)

# total de sentence_ids únicos
total_sentences = df["sentence_id"].nunique()

# --- Sentence_ids por keyword e autor ---
grouped = (
    df.groupby(["keywords", "author"])["sentence_id"]
    .apply(set)
    .unstack(fill_value=set())
)

# garantir colunas
for col in ["Mises", "Hayek"]:
    if col not in grouped.columns:
        grouped[col] = grouped.apply(lambda x: set(), axis=1)

# --- contagens reais ---
grouped["n_Mises"] = grouped["Mises"].apply(len)
grouped["n_Hayek"] = grouped["Hayek"].apply(len)

grouped["n_both"] = grouped.apply(
    lambda row: len(row["Mises"].intersection(row["Hayek"])),
    axis=1
)

grouped["n_total_keyword"] = grouped.apply(
    lambda row: len(row["Mises"].union(row["Hayek"])),
    axis=1
)

# --- probabilidades reais ---
grouped["P(Mises)"] = grouped["n_Mises"] / total_sentences
grouped["P(Hayek)"] = grouped["n_Hayek"] / total_sentences

grouped["P(Mises and Hayek)"] = grouped["n_both"] / total_sentences

grouped["P(Mises only)"] = (
    (grouped["n_Mises"] - grouped["n_both"]) / total_sentences
)

grouped["P(Hayek only)"] = (
    (grouped["n_Hayek"] - grouped["n_both"]) / total_sentences
)

# --- probabilidades condicionais reais ---
grouped["P(Mises | Hayek)"] = np.where(
    grouped["n_Hayek"] > 0,
    grouped["n_both"] / grouped["n_Hayek"],
    0
)

grouped["P(Hayek | Mises)"] = np.where(
    grouped["n_Mises"] > 0,
    grouped["n_both"] / grouped["n_Mises"],
    0
)

# --- tabela final ---
keyword_table = (
    grouped[
        [
            "P(Mises)",
            "P(Hayek)",
            "P(Mises and Hayek)",
            "P(Mises only)",
            "P(Hayek only)",
            "P(Mises | Hayek)",
            "P(Hayek | Mises)"
        ]
    ]
    .reset_index()
    .rename(columns={"keywords": "keyword"})
    .sort_values("keyword")
)

keyword_table

author,keyword,P(Mises),P(Hayek),P(Mises and Hayek),P(Mises only),P(Hayek only),P(Mises | Hayek),P(Hayek | Mises)
0,'entrepreneurship'],0.000303,0.000227,0.000076,0.000227,0.000152,0.333333,0.250000
1,['business cycle'],0.009092,0.008864,0.003485,0.005606,0.005379,0.393162,0.383333
2,['entrepreneurship'],0.014547,0.004243,0.002046,0.012501,0.002197,0.482143,0.140625
3,['innovation',0.000227,0.000227,0.000076,0.000152,0.000152,0.333333,0.333333
4,['innovation'],0.001061,0.000682,0.000152,0.000909,0.000530,0.222222,0.142857
5,['knowledge problem'],0.000530,0.002652,0.000303,0.000227,0.002349,0.114286,0.571429
6,['praxeology',0.000076,0.000000,0.000000,0.000076,0.000000,0.000000,0.000000
7,['praxeology'],0.020305,0.001288,0.000227,0.020077,0.001061,0.176471,0.011194
8,[],0.531707,0.449276,0.038488,0.493219,0.410789,0.085666,0.072385

Log-Likelihood

In [22]:
import re

# Load allowed keywords once (do this outside tokenize)
keywords_df = pd.read_csv("keywords_austrian_papers.csv")

# Normalize keywords the same way as tokenize does
allowed_keywords = set()

for kws in keywords_df["Author Keywords"].dropna():
    for kw in str(kws).split(";"):  # assuming keywords are separated by ;
        kw = kw.strip().lower()
        kw = re.sub(r'[^a-zA-Z\s]', ' ', kw)
        allowed_keywords.add(kw)

allowed_keywords

{'phillips curve',
 'cognitive science',
 'merger waves',
 'bertrand competition',
 'individual rights',
 'bank clearinghouse',
 'subjective v  objective probability',
 'corporate control',
 'katallactics',
 'federalism and polycentricity',
 'deficits',
 'intertemporal coordination failure',
 'social ecological systems',
 'labor',
 'knowledge problem',
 'behavioral political economy',
 'local government',
 'business groups',
 'insider information',
 'role of government',
 'no fault divorce',
 'israel kirzner',
 'causal theory of mind',
 'time to build',
 'artistic genius',
 'gdp',
 'modernism',
 'interdependence',
 'social theory',
 'modern art',
 'eudaimonia',
 'economics of the arts',
 'theory and history',
 'austrian approach',
 'cluster',
 'interest',
 'witness',
 'arts',
 'peasant economy',
 'the firm',
 'power as mass phenomenon',
 'karl menger              ',
 'firm governance',
 'proficiency test',
 'capital',
 'prejudice',
 'social ontology',
 'hebb',
 'consumption tax',
 'gudeman',
 'division of knowledge in society',
 'exchange paradigm',
 'war socialism',
 'organization of markets',
 'social capital',
 'public finance',
 'sunk costs',
 'thick descriptions',
 'london school of economics',
 'nominal income targeting',
 'public private partnerships',
 'q  ',
 'classical economist',
 'tax strategies',
 'living standards',
 'corporatism',
 'fractional reserve banking',
 'money',
 'human action',
 'panic of     ',
 'emergent order',
 'network theory',
 'designer drugs',
 'credit and money multipliers',
 'platform economy',
 'cronyism',
 'ludwig von mises',
 'time series forecasting',
 'red cross',
 'financial instability',
 'austrian chicago synthesis  law and economics',
 'social structures',
 'reciprocity',
 'individual state relations',
 'austrian program',
 'honor culture',
 'individualistic view',
 'externalities',
 'liberal transition',
 'healthcare',
 'the economy of knowledge',
 'business cycle',
 'morality',
 'racism',
 'experimental epistemology',
 'j  s  mill',
 'mccloskey',
 'baltic sea area',
 'game mining',
 'public reason',
 'export processing zones',
 'exploratory data analysis',
 'self direction',
 'skyscraper curse',
 'impossible world',
 'gdp growth',
 'mathematical praxeology',
 'incentive compatibility',
 'spain',
 'conflict and political economy',
 'cybersecurity economics',
 'kirznerian entrepreneurship',
 'memory',
 'measurements',
 'catallactics',
 'suboptimal conditions',
 'comparative economics',
 'solow growth model',
 'john maynard keynes',
 'ideology',
 'wage cyclicality',
 'english constitutional history',
 'natural volatility',
 'socialization of investment',
 'p ',
 'brexit',
 'l  ',
 'superstorm sandy',
 'land use planning',
 'accounting',
 'cryptoeconomics',
 'social needs',
 'piketty',
 'financial regulation',
 'gdp gap',
 'employment',
 'applied research',
 'gift exchange',
 'words',
 'rigidities',
 'plan disequilibrium',
 'keynesian multiplier',
 'fatal conceit',
 'institutional analysis',
 'volatility',
 'pure theory',
 'neo schumpeterian economics',
 'mathematical foundations of economics',
 'cantillon effects',
 'gender specifica',
 'nation building',
 'collective goods',
 'social democracy',
 'emergentism',
 'classical economics',
 'gary becker',
 'state legitimacy',
 'b hm bawerk',
 'feudal economy',
 'fitting attitude theory',
 'scientific communities',
 'self immolation',
 'psychologism',
 'hayekian triangle',
 'social darwinism',
 'hyperinflation',
 'subjectivist interpretation',
 'reswitching',
 'business cycle theory',
 'legal institutions',
 'central planning systems',
 'monitoring',
 'lag length',
 'disequilibrium',
 'interpretation',
 'developing countries',
 'nudge theory',
 'equity',
 'uncertainty bearing',
 'political equilibrium',
 'nonprice coordination',
 'boom',
 'heterodoxy',
 'finance',
 'property rights',
 'market signal',
 'homogeneity',
 'identity rules',
 'social status',
 'incentive problem',
 'great enrichment',
 'keynesian economics',
 'cycles bankruptcy',
 'price level stabilization',
 'equality',
 'statism',
 'karl popper',
 'civic associations',
 'connectionism',
 'housing',
 'bureaucracy',
 'corporate governance',
 'cartesian rationalism',
 'regulatory models',
 'bank reserves',
 'interjurisdictional competition',
 'economic laws',
 'insider trading',
 'central bank independence',
 'social order',
 'market rate of interest',
 'control of politicians',
 'property rights entrepreneurship',
 'justification',
 'replacement',
 'social economics',
 'bottom up dynamics',
 'non equilibrium processes',
 'malcom mclean',
 'embeddedness',
 'innovation policy',
 'rutledge vining',
 'recession',
 'functionalism',
 'asset price inflation',
 'deregulation',
 'rationality',
 'non neutral money',
 'temporary equilibrium',
 'heterogeneous population groups',
 'hyman minsky',
 'normative individualism',
 're switching of techniques',
 'national bureau of economic research',
 'lucas',
 'yield curve',
 'cryptocurrency',
 'roger w  garrison',
 'opportunity discovery',
 'social problems',
 'self regulation',
 'deductivism',
 'international trade',
 'school of salamanca',
 'private provision of public goods',
 'crime',
 'marriage specific human capital',
 'positional good',
 'liquidation',
 'experts',
 'post disaster recovery',
 'public entrepreneurship',
 'romania',
 'heterodox practices',
 'utilization',
 'agriculture',
 'nonneutrality of money',
 'military history',
 'financial markets',
 'gold standard',
 'population',
 'adjustment',
 'life science',
 'dodd frank',
 'social peace',
 'public administration',
 'innovation systems',
 'ordoliberalism',
 'rule following',
 'aristotle',
 'behavioral paternalism',
 'bentham',
 'mainline economics',
 'land use regulations',
 'interwar vienna',
 'etiquette',
 'scholasticism',
 'virginia school',
 'wealth',
 'buchanan',
 'mysticism',
 'monetary footprint',
 'supply curve',
 'the sensory order',
 'statelessness',
 'lax fiscal policy',
 'capital based macroeconomics',
 'brentano',
 'rothbard',
 'carl schmitt',
 'golden rule',
 'refinancing',
 'interest rate brake',
 'el mercurio',
 'instruments of interpretation',
 'pure time preference theory of interest',
 'digital platforms',
 'sense of place',
 'friedrich hayek',
 'peter boettke',
 'neo mengerian',
 'interdisciplinary applications',
 'agent based modeling',
 'thymology',
 'securitization',
 'polish lithuanian commonwealth',
 'beveridge',
 'arbitrage',
 'schools of thought',
 'cognition',
 'cooperatives',
 'interpretive schema',
 'anarchism',
 'austrian business cycle model',
 'meanings',
 'methodology',
 'classical liberal',
 'path dependence',
 'destutt de tracy',
 'superfluous discovery',
 'cerebral cortex',
 'centralized mindset',
 'wages fund',
 'time structure of capital',
 'financial crisis',
 'scheall',
 'neoclassical theory of production',
 'augusto pinochet',
 'monetary systems',
 'language',
 'decision making ability',
 'marriage',
 'environmentalism',
 'institutionalism',
 'organized crime',
 'herding',
 'pricespecie flow mechanism',
 'perverse preferences',
 'order dependent knowledge',
 'economic history',
 'austrian school of economics  origins of the ',
 'environmental kuznets curve',
 'open source software',
 'pareto optimality',
 'bayesian surprise',
 'agency theory',
 'counterfactual reasoning',
 'central and eastern europe',
 'calibration',
 'influence on the profession',
 'conventions',
 'choice',
 'overshooting',
 'economic policy',
 'aggregation bias',
 'local knowledge',
 'neurath',
 'marginal efficiency of capital',
 'collaborative innovation blocs',
 'var',
 'john stuart mill',
 'folk psychology',
 'east of eden',
 'institutional economics',
 'big push',
 'west germany',
 'catallaxy',
 'post communist state',
 'ronald coase',
 'tocqueville',
 'public choice',
 'common pool resource',
 'anarchy',
 'hierarchical cognitive organization',
 'kaleidics vs  equilibrium',
 'production structure',
 'b r  shenoy',
 'ethical theory',
 'developmental state',
 'housing boom',
 'autonomy of the political',
 'search costs',
 'covenant',
 'dsge models',
 'consistency',
 'realist social theory',
 'increasing returns',
 'persecution and toleration',
 'civic capital',
 'equilibrium constructs',
 'eugen schmalenbach',
 'mercantilism',
 'private vs  public ordering',
 'theories of the firm',
 'nonequilibrium theory',
 'smart contracts',
 'sociology',
 'spinoza',
 'interest rates',
 'hayek s challenge',
 'knowledge',
 'milton friedman',
 'concept',
 'virtues',
 'denationalization of money',
 'history of economic thought',
 'firrea',
 'hayekian business cycle theory',
 'socialist systems',
 'labor intensity',
 'plan coordination',
 'creative systems theory',
 'welfare economics',
 'contract curve',
 'policy',
 'austrian school',
 'friedrich a  von hayek',
 'cultural diversity',
 'efficiency',
 'keynesian demand constraint',
 'adam smith',
 'mainstream heterodoxy',
 'search',
 'free enterprise system',
 'fed',
 'tennessee',
 'carl menger',
 'doux commerce thesis',
 'z ',
 'demand for heterogeneous goods',
 'externalities as profit opportunities',
 'police misconduct',
 'aristotelianism',
 'organization',
 'administrative law',
 'culture and economy',
 'specialization',
 'political market',
 'j  ',
 'federalism',
 'multiplier',
 'decentralization',
 'discrimination',
 'market processes',
 'national defense',
 'assurance',
 'cost of trust',
 'real factor price frontier',
 'law and economics',
 'natural rate of interest',
 'international business cycle',
 'regulation as taxation',
 'monetary non neutrality',
 'perfect foresight',
 'invest',
 'principles of economics',
 'b  b  e  p ',
 'fisheries',
 'economic fluctuations',
 'trust game',
 'consumers  good',
 'quantum brain',
 'supplier specificity',
 'deontology',
 'financial economics',
 'german business economics',
 'analytical egalitarianism',
 'precautionary reserves',
 'pattern predictions',
 'cointegration',
 'walrasian',
 'individual choice',
 'predictive analytics',
 'evolutionary game theory',
 'murray rothbard',
 'assets',
 'macroeconomic policy',
 'induced volatility',
 'capital theory',
 'the theory of the firm',
 'profit',
 'general equilibrium',
 'institutional change',
 'insurance',
 'business fluctuations',
 'democratic republic of the congo',
 'c  s  peirce',
 'i ',
 'socialist thought',
 'intertertemporal coordination',
 'epistemic turn',
 'diversity',
 'verstehen',
 'growth',
 'ideology ideas',
 'disasters',
 'speculation',
 'preference',
 'o  ',
 'limited government',
 'bust',
 'politics',
 'history and theory',
 'measurement',
 'pre modern world',
 'comparative institutional analysis',
 'relational code',
 'regulated oligopoly',
 'new york university',
 'abct',
 '     crisis',
 'oregon',
 'performance of government',
 'cross country divergences',
 'blue wall of silence',
 'impulse response',
 'truthful revelation',
 'coordination as process',
 'price',
 'analytical anarchism',
 'microeconomic theory',
 'action',
 'lindahl',
 'polycentric governance',
 'subjectivity within objectivism',
 'george selgin',
 'obsolescence',
 'autonomy',
 'austrian',
 'james otteson',
 'fiscal policy',
 'free market',
 'cost accounting',
 'b   austrian economics',
 'efficiency wages',
 'macroeconomic forecasts',
 'praxeological theory of politics',
 'nationalism',
 'triadic exchange',
 'constitutionalism',
 'immigration',
 'doctrinal history',
 'neutral money',
 'deposit insurance',
 'research and development',
 'social preferences',
 'critical rationalism',
 'arrow debreu mckenzie model',
 'organismic view',
 'populism',
 'sociality',
 'ecology of plans',
 'central banks',
 'mont p lerin society',
 'relevancy',
 'is lm model',
 'fritz machlup',
 'scenario building',
 'knight bowles gintis contested exchange',
 'welfare',
 'the market process',
 'prosocial behavior',
 'institutional development',
 'analytic narrative',
 'austrian economics',
 'term structure of interest rates',
 'dyadic exchange',
 'state of confidence',
 'consumer wants',
 'monetary equilibrium',
 'tohoku',
 'credit expansion',
 'capital structure',
 'salience imbalance',
 'labor markets',
 'constitutional drift',
 'crowding out',
 'economic models',
 'collusion',
 'leviathan',
 'economist',
 'tacit knowledge',
 'taxation',
 'aquinas',
 'psychology',
 'designed orders',
 'gross market rate of interest',
 'deflation',
 'co operatives',
 'wagner s law',
 'bargaining',
 'housing first',
 'disaster',
 'takeover bids',
 'interventions',
 'theory of the firm',
 'john rawls',
 'collaborative innovation bloc',
 'monetarism',
 'h lsmann',
 'austrian chicago synthesis',
 'history of scotland',
 'unawareness  k   cyber law',
 'frankfurt school',
 'ricardo effect',
 'noncomprehensive planning',
 'profits and losses',
 'subprime crisis',
 'institutional competition',
 'complexity',
 'structure',
 'lock in',
 'commercial culture',
 'qualitative methods',
 'dualism',
 'computationalism',
 'service life',
 'spontaneous order theorizing',
 'pattern coordination',
 'victimhood culture',
 'swedberg',
 'slovenia',
 'expectations',
 'transitional economics',
 'intelligence',
 'utilitarianism',
 'prudence',
 'reputational information and technology',
 'james m  buchanan',
 'f a hayek',
 'failed states',
 'interest rate sensitivity',
 'monetary theory',
 'circular flow model',
 'product quality',
 'competitive advantage',
 'precautionary assets',
 'housing market',
 'north',
 'price system',
 'legal order',
 'industrial organization',
 'hayek',
 'containerization',
 ' post austrian  economics',
 'interpretive rationality',
 'real business cycle theory',
 'theory of science',
 'principal agent',
 'public economics and public choice',
 'computational social science',
 'calculation',
 'coase',
 'stock',
 'transition',
 'quadratic voting',
 'prisoner s dilemma',
 'state building',
 'side payments',
 'weber',
 'fraud prevention',
 'originality',
 'conflict',
 'action space',
 'william stanley jevons',
 'morality  metaethics',
 'hayek s paradox',
 'elinor ostrom',
 'competition as rivalry process',
 'european sovereign debt',
 'amherst school',
 'accountant',
 'development planning',
 'austrian economist',
 'progressive tax',
 'great recession',
 'in kind donations',
 'stakeholder socialism',
 'categorizations',
 'regression discontinuity',
 'regime uncertainty',
 'emergence',
 'capital longevity',
 'mach',
 'price premium',
 'marketing',
 'dictatorship',
 'rent seeking',
 'new orleans',
 'adolf wagner',
 'sensation',
 'constitutional law',
 'development economics',
 'biography',
 'panel data',
 'gifts',
 'financial innovation',
 'evolutionary economics',
 'sclerosis',
 'health',
 'cognitive closure',
 'argument',
 'g  warren nutter',
 'invisible hand',
 'philosophy',
 'evolution of government',
 'rational choice',
 'local and community currency',
 'teleological perspective',
 'marginal utility theory',
 'libertarianism',
 'enactivism',
 'economic methodologies',
 'garrison',
 'undecidability and choice',
 'pretence of knowledge',
 'royal navy',
 'low income families',
 'dynamics of the mixed economy',
 'ownership function',
 'f  a  hayek mock trial',
 'urban growth',
 'israel m  kirzner',
 'f a  hayek',
 'economic value added',
 'neo liberalism',
 'use of knowledge',
 'schools in economic thought',
 'economic freedom',
 'pandemics',
 'resilience',
 'demand',
 'power problem',
 'pareto efficient',
 'objectivism',
 'ceteris paribus',
 'division of labor',
 'legal systems',
 'gr nberg',
 'competition',
 'housing bubble',
 'nudge',
 'myrdal',
 'terrorism',
 'statogenic climate change',
 'tax backing theory of money',
 'entrepreneurs',
 'intra industry trade',
 'empirical',
 'causal ambiguity',
 'sweden',
 'rural land use policy',
 'say  jean baptiste ',
 'market epistemology',
 'subjectivism',
 'economic anthropology',
 'indian economic development',
 'co ordination',
 'natural selection',
 'regulation',
 'marxian socialism',
 'k   https   www aeaweb org jel guide jel php',
 'tuism',
 'new comparative economics',
 'deposits',
 'exogenous innovation',
 'counterfactuals',
 'rawls',
 'law',
 'monetary policy',
 'alfred schutz',
 'interpretive framework',
 'ottoman and balkans monetary history',
 'water supply',
 'entrepreneurial inspiration',
 'public policy',
 'credit markets as coercive exchange',
 'big data',
 'modularity',
 'credit booms',
 'de banking',
 'tax revenue',
 'transmission channel',
 'federal reserve policy',
 'industrial planning',
 'ludwig lachmann',
 'the cultural economic perspective',
 'strategy',
 'globalization',
 'tradable emissions permits',
 'contractarianism',
 'goedel s theorem',
 'value of the firm',
 'chinese reforms',
 'rights',
 'family values   political economy of family   neoliberalism   social conservatism',
 'capitalist ethic',
 'settlement changes',
 'social space',
 'austrian business cycle theory',
 'entangled political economy',
 'purpose orientation',
 'financial crises',
 'evolutionism',
 'bloomington school',
 'economics of digital privacy',
 'perfect competition',
 'irrational exuberance',
 'arbitrariness',
 'collective action',
 'wilhelm r pke',
 'empirical labour theory of value',
 'teaching',
 'social dilemmas',
 'monetary policy and interest rates',
 'stock market',
 'embodied knowledge',
 'epistemic community',
 'discovery',
 'bellagio group',
 'justice',
 'and economics',
 'justified true belief',
 'team production',
 'marketplace of ideas',
 'heterogeneous capital',
 'benevolence',
 'dynamic rent seeking',
 'polycentric institutions',
 'embodied cognition',
 'lithuania',
 'chaos theory',
 'trade',
 'avant garde',
 'india',
 'controlled substances act',
 'motivation',
 'roundaboutness',
 'value investing',
 'savings',
 'human sociality',
 'monetary rewards',
 'prosperity',
 'regional development',
 'civilization',
 'natural resources',
 'appraisal optimism',
 'adaptation',
 'dynamics on interventionism',
 'special economic zones',
 'laissez faire',
 'positive legislation',
 'republic of science',
 'environmental economics',
 'economic welfare',
 'statistical inference',
 'time and economics',
 'social distance',
 'depression of          ',
 'social cohesion',
 'behaviorism',
 'payment processing',
 'post conflict reconstruction',
 'crisis',
 'akrasia',
 'computers',
 'general laws',
 'pdl',
 'production contracts',
 'value paradigm',
 'center for the study of market processes',
 'central european history',
 'time and ignorance',
 'think tanks',
 'cognitive bias',
 'causality',
 'bitcoin',
 'traveler s tale',
 'fisher effect',
 'fractional reserves',
 'combinations',
 'menger  carl ',
 'leeson',
 'peru',
 'capital complexity',
 'freedom',
 'economic method',
 'cognitive institutions',
 'repressed inflation',
 'comparative systems',
 'constitutional maintenance',
 'kaleidic economy',
 'transparency',
 'innovativeness',
 'private schools',
 'interbank clearing',
 'class structure',
 'exit vs  voice',
 'needs',
 'weak states',
 'induced malnovation',
 'paul samuelson',
 'economic geography',
 'anarcho capitalism',
 'realism',
 'armen alchian',
 'polycentricity',
 'fractal analysis',
 'turning point',
 'praxeology',
 'problem definition',
 'income',
 'price gouging',
 'minsky',
 'depreciation',
 'austrian business cycle',
 'decision making',
 'hicks',
 'economic pedagogy',
 'regression theorem',
 'predatory state',
 'climate',
 'brazil',
 'evolutionary epistemology',
 'comparative analysis',
 'check certification',
 'gresham s law',
 'non price parameters of goods and services',
 'ideas and institutions',
 'incentives',
 'action axiom',
 'time preference',
 'ethics',
 'gunnar myrdal',
 'self interest',
 'hysteresis',
 'common law',
 'indian economic thought',
 'private property rights',
 'complex adaptive systems',
 'keynesianism',
 'neoliberalism',
 'ucla tradition',
 'non equilibrium theory',
 'regions',
 'fiduciary duties of investment advisors and broker dealers',
 'industrial policy',
 'cantillon effect',
 'dimensions of operators and variables',
 'extended order',
 'rule of law',

In [23]:
mises_only_df = mises_citations_df[
    (mises_citations_df['co_cited_count'] == 0)
]

hayek_only_df = hayek_citations_df[
    (hayek_citations_df['co_cited_count'] == 0)
]

mises_hayek_df = mises_citations_df[
    (mises_citations_df['co_cited_count'] > 0)
]


import math
import re
from collections import Counter
import pandas as pd

# -------------------------
# Tokenização simples
# -------------------------
def tokenize(text):
    text = text.lower()
    text = re.sub(r'[^a-zA-Z\s]', ' ', text)

    tokens = text.split()

    return [t for t in tokens if t in allowed_keywords]



# -------------------------
# Agregação por unidade
# -------------------------
def aggregate_text(df, group_col):
    return (
        df.groupby(group_col)['context']
        .apply(lambda x: ' '.join(x))
        .dropna()
    )


# -------------------------
# Construir Counter
# -------------------------
def build_counter(text_series):
    tokens = []
    for text in text_series:
        tokens.extend(tokenize(text))
    return Counter(tokens)


# -------------------------
# LLR binário
# -------------------------
def compute_llr(counter_a, counter_b, label_a, label_b):
    results = []
    
    total_a = sum(counter_a.values())
    total_b = sum(counter_b.values())
    
    vocab = set(counter_a.keys()).union(counter_b.keys())
    
    for word in vocab:
        k1 = counter_a.get(word, 0)
        k2 = counter_b.get(word, 0)
        
        if k1 == 0 and k2 == 0:
            continue
        
        E1 = total_a * (k1 + k2) / (total_a + total_b)
        E2 = total_b * (k1 + k2) / (total_a + total_b)
        
        score = 0
        if k1 > 0:
            score += k1 * math.log(k1 / E1)
        if k2 > 0:
            score += k2 * math.log(k2 / E2)
        
        score *= 2
        
        prop_a = k1 / total_a if total_a > 0 else 0
        prop_b = k2 / total_b if total_b > 0 else 0
        
        dominant = label_a if prop_a > prop_b else label_b
        
        results.append((word, score, dominant))
    
    return pd.DataFrame(results, columns=["word", "llr_score", "dominant_in"])\
             .sort_values("llr_score", ascending=False)


# -------------------------
# Função geral
# -------------------------
def run_pairwise_llr(df_a, df_b, label_a, label_b, group_col):
    
    agg_a = aggregate_text(df_a, group_col)
    agg_b = aggregate_text(df_b, group_col)
    
    counter_a = build_counter(agg_a)
    counter_b = build_counter(agg_b)
    
    return compute_llr(counter_a, counter_b, label_a, label_b)

In [24]:

# ===========================
# 🚀 EXECUÇÃO POR SENTENCE_ID
# ===========================

# 1️⃣ Mises-only vs Hayek-only
llr_mh = run_pairwise_llr(
    mises_only_df,
    hayek_only_df,
    "Mises-only",
    "Hayek-only",
    group_col="sentence_id"
)

# 2️⃣ Mises-only vs Mises+Hayek
llr_mm = run_pairwise_llr(
    mises_only_df,
    mises_hayek_df,
    "Mises-only",
    "Mises+Hayek",
    group_col="sentence_id"
)

# 3️⃣ Hayek-only vs Mises+Hayek
llr_hm = run_pairwise_llr(
    hayek_only_df,
    mises_hayek_df,
    "Hayek-only",
    "Mises+Hayek",
    group_col="sentence_id"
)

print("Mises vs Hayek")
print(llr_mh.head(30))

print("Mises vs Co-cited")
print(llr_mm.head(30))

print("Hayek vs Co-cited")
print(llr_hm.head(30))

Mises vs Hayek
                 word    llr_score dominant_in
134             hayek  8189.771819  Hayek-only
295             mises  7397.727491  Mises-only
183         knowledge   496.862169  Hayek-only
364            action   384.322362  Mises-only
234             rules   319.426399  Hayek-only
136        praxeology   190.579121  Mises-only
236       information   148.655130  Hayek-only
181     individualism   133.530416  Hayek-only
94       entrepreneur   132.734781  Mises-only
270       competition   116.744715  Hayek-only
147       calculation   103.752597  Mises-only
1           discovery   102.809764  Hayek-only
103             money    96.164468  Mises-only
298          exchange    93.783455  Mises-only
7      classification    77.234983  Hayek-only
288       probability    74.474879  Mises-only
29        equilibrium    69.878669  Hayek-only
25              labor    68.792875  Mises-only
283      coordination    67.469981  Hayek-only
293            profit    64.090605  Mises-only
89            liberty    62.583731  Hayek-only
201             value    60.226305  Mises-only
92       institutions    52.207470  Hayek-only
59          evolution    50.132762  Hayek-only
97         complexity    48.421505  Hayek-only
144  entrepreneurship    48.103702  Mises-only
93            process    46.126643  Hayek-only
383             goods    45.617086  Mises-only
375       cooperation    45.191332  Mises-only
260         socialism    44.424221  Mises-only
Mises vs Co-cited
                 word    llr_score  dominant_in
136             hayek  1036.893704  Mises+Hayek
213           kirzner   483.527719  Mises+Hayek
31           rothbard   469.159478  Mises+Hayek
298             mises   263.179346   Mises-only
385          lachmann   142.904902  Mises+Hayek
61            boettke    96.414833  Mises+Hayek
314            menger    89.871896  Mises+Hayek
234          garrison    89.266563  Mises+Hayek
8          schumpeter    89.243881  Mises+Hayek
389             goods    88.987398   Mises-only
387          austrian    87.845258  Mises+Hayek
371            action    62.936820   Mises-only
17           buchanan    56.928405  Mises+Hayek
97              money    54.910897   Mises-only
147  entrepreneurship    52.869416  Mises+Hayek
235            lavoie    49.704863  Mises+Hayek
21              labor    47.785612   Mises-only
161        production    38.841372   Mises-only
0           discovery    38.557503  Mises+Hayek
277             rizzo    35.774530  Mises+Hayek
266         socialism    34.316270   Mises-only
106            leeson    29.346035  Mises+Hayek
51             prices    28.530906   Mises-only
243    disequilibrium    26.400744  Mises+Hayek
211             value    25.705672   Mises-only
240              land    25.355358   Mises-only
55            capital    24.321257   Mises-only
196        employment    24.282409   Mises-only
302          exchange    23.840744   Mises-only
58             keynes    22.846482  Mises+Hayek
Hayek vs Co-cited
                 word    llr_score  dominant_in
309             mises  4683.480007  Mises+Hayek
139             hayek  3321.569631   Hayek-only
35           rothbard   503.611487  Mises+Hayek
212           kirzner   413.759572  Mises+Hayek
190         knowledge   383.305595   Hayek-only
246             rules   214.581999   Hayek-only
149  entrepreneurship   165.337320  Mises+Hayek
397          austrian   140.880487  Mises+Hayek
382            action   123.032325  Mises+Hayek
394          lachmann   115.362804  Mises+Hayek
141        praxeology   112.629715  Mises+Hayek
284       competition   106.094433   Hayek-only
69            boettke   104.032825  Mises+Hayek
95       entrepreneur    96.660873  Mises+Hayek
188     individualism    74.138076   Hayek-only
10         schumpeter    66.215878  Mises+Hayek
165             weber    65.007812  Mises+Hayek
236            lavoie    61.871065  Mises+Hayek
7      classification    61.231290   Hayek-only
385       uncertainty    59.033507  Mises+Hayek
325               law    54.862204   Hayek-only
248       information    54.791341   Hayek-only
89            liberty    51.414472   Hayek-only
324            menger    46.287060  Mises+Hayek
93       institutions    38.904640   Hayek-only
235          garrison    37.031716  Mises+Hayek
297      coordination    32.869272   Hayek-only
67             orders    31.409968   Hayek-only
328          coercion    30.177515   Hayek-only
355         selection    30.177515   Hayek-only

In [25]:
# ==========================
# 🔥 EXECUÇÃO POR PARAGRAPH_ID
# ==========================

# 1️⃣ Mises-only vs Hayek-only
llr_mh_paragraph = run_pairwise_llr(
    mises_only_df,
    hayek_only_df,
    "Mises-only",
    "Hayek-only",
    group_col="paragraph_id"
)

# 2️⃣ Mises-only vs Mises+Hayek
llr_mm_paragraph = run_pairwise_llr(
    mises_only_df,
    mises_hayek_df,
    "Mises-only",
    "Mises+Hayek",
    group_col="paragraph_id"
)

# 3️⃣ Hayek-only vs Mises+Hayek
llr_hm_paragraph = run_pairwise_llr(
    hayek_only_df,
    mises_hayek_df,
    "Hayek-only",
    "Mises+Hayek",
    group_col="paragraph_id"
)


print("Paragraph Level — Mises vs Hayek")
print(llr_mh_paragraph.head(30))

print("Paragraph Level — Mises vs Co-cited")
print(llr_mm_paragraph.head(30))

print("Paragraph Level — Hayek vs Co-cited")
print(llr_hm_paragraph.head(30))

Paragraph Level — Mises vs Hayek
                 word    llr_score dominant_in
134             hayek  8189.771819  Hayek-only
295             mises  7397.727491  Mises-only
183         knowledge   496.862169  Hayek-only
364            action   384.322362  Mises-only
234             rules   319.426399  Hayek-only
136        praxeology   190.579121  Mises-only
236       information   148.655130  Hayek-only
181     individualism   133.530416  Hayek-only
94       entrepreneur   132.734781  Mises-only
270       competition   116.744715  Hayek-only
147       calculation   103.752597  Mises-only
1           discovery   102.809764  Hayek-only
103             money    96.164468  Mises-only
298          exchange    93.783455  Mises-only
7      classification    77.234983  Hayek-only
288       probability    74.474879  Mises-only
29        equilibrium    69.878669  Hayek-only
25              labor    68.792875  Mises-only
283      coordination    67.469981  Hayek-only
293            profit    64.090605  Mises-only
89            liberty    62.583731  Hayek-only
201             value    60.226305  Mises-only
92       institutions    52.207470  Hayek-only
59          evolution    50.132762  Hayek-only
96         complexity    48.421505  Hayek-only
144  entrepreneurship    48.103702  Mises-only
93            process    46.126643  Hayek-only
383             goods    45.617086  Mises-only
375       cooperation    45.191332  Mises-only
260         socialism    44.424221  Mises-only
Paragraph Level — Mises vs Co-cited
                 word    llr_score  dominant_in
136             hayek  1036.893704  Mises+Hayek
213           kirzner   483.527719  Mises+Hayek
31           rothbard   469.159478  Mises+Hayek
298             mises   263.179346   Mises-only
385          lachmann   142.904902  Mises+Hayek
61            boettke    96.414833  Mises+Hayek
314            menger    89.871896  Mises+Hayek
234          garrison    89.266563  Mises+Hayek
8          schumpeter    89.243881  Mises+Hayek
389             goods    88.987398   Mises-only
387          austrian    87.845258  Mises+Hayek
371            action    62.936820   Mises-only
17           buchanan    56.928405  Mises+Hayek
97              money    54.910897   Mises-only
147  entrepreneurship    52.869416  Mises+Hayek
235            lavoie    49.704863  Mises+Hayek
21              labor    47.785612   Mises-only
161        production    38.841372   Mises-only
0           discovery    38.557503  Mises+Hayek
277             rizzo    35.774530  Mises+Hayek
266         socialism    34.316270   Mises-only
106            leeson    29.346035  Mises+Hayek
51             prices    28.530906   Mises-only
243    disequilibrium    26.400744  Mises+Hayek
211             value    25.705672   Mises-only
240              land    25.355358   Mises-only
56            capital    24.321257   Mises-only
196        employment    24.282409   Mises-only
302          exchange    23.840744   Mises-only
58             keynes    22.846482  Mises+Hayek
Paragraph Level — Hayek vs Co-cited
                 word    llr_score  dominant_in
309             mises  4683.480007  Mises+Hayek
139             hayek  3321.569631   Hayek-only
35           rothbard   503.611487  Mises+Hayek
212           kirzner   413.759572  Mises+Hayek
190         knowledge   383.305595   Hayek-only
246             rules   214.581999   Hayek-only
149  entrepreneurship   165.337320  Mises+Hayek
397          austrian   140.880487  Mises+Hayek
382            action   123.032325  Mises+Hayek
394          lachmann   115.362804  Mises+Hayek
141        praxeology   112.629715  Mises+Hayek
283       competition   106.094433   Hayek-only
69            boettke   104.032825  Mises+Hayek
95       entrepreneur    96.660873  Mises+Hayek
188     individualism    74.138076   Hayek-only
12         schumpeter    66.215878  Mises+Hayek
165             weber    65.007812  Mises+Hayek
236            lavoie    61.871065  Mises+Hayek
7      classification    61.231290   Hayek-only
385       uncertainty    59.033507  Mises+Hayek
325               law    54.862204   Hayek-only
248       information    54.791341   Hayek-only
89            liberty    51.414472   Hayek-only
324            menger    46.287060  Mises+Hayek
93       institutions    38.904640   Hayek-only
235          garrison    37.031716  Mises+Hayek
297      coordination    32.869272   Hayek-only
67             orders    31.409968   Hayek-only
328          coercion    30.177515   Hayek-only
355         selection    30.177515   Hayek-only

In [26]:
# ==========================
# 🔥 EXECUÇÃO POR SECTION_ID
# ==========================

# 1️⃣ Mises-only vs Hayek-only
llr_mh_section = run_pairwise_llr(
    mises_only_df,
    hayek_only_df,
    "Mises-only",
    "Hayek-only",
    group_col="section_id"
)

# 2️⃣ Mises-only vs Mises+Hayek
llr_mm_section = run_pairwise_llr(
    mises_only_df,
    mises_hayek_df,
    "Mises-only",
    "Mises+Hayek",
    group_col="section_id"
)

# 3️⃣ Hayek-only vs Mises+Hayek
llr_hm_section = run_pairwise_llr(
    hayek_only_df,
    mises_hayek_df,
    "Hayek-only",
    "Mises+Hayek",
    group_col="section_id"
)


print("Section Level — Mises vs Hayek")
print(llr_mh_section.head(30))

print("Section Level — Mises vs Co-cited")
print(llr_mm_section.head(30))

print("Section Level — Hayek vs Co-cited")
print(llr_hm_section.head(30))

Section Level — Mises vs Hayek
                 word    llr_score dominant_in
134             hayek  8049.470382  Hayek-only
295             mises  7316.909454  Mises-only
183         knowledge   492.693281  Hayek-only
364            action   378.307505  Mises-only
234             rules   314.834572  Hayek-only
136        praxeology   186.418239  Mises-only
236       information   147.148716  Hayek-only
181     individualism   144.414398  Hayek-only
94       entrepreneur   127.870088  Mises-only
270       competition   121.548361  Hayek-only
147       calculation   113.592284  Mises-only
1           discovery   102.714905  Hayek-only
298          exchange    90.417125  Mises-only
103             money    84.553712  Mises-only
7      classification    77.162551  Hayek-only
288       probability    74.561824  Mises-only
29        equilibrium    72.528935  Hayek-only
25              labor    68.886496  Mises-only
283      coordination    67.403149  Hayek-only
293            profit    64.177968  Mises-only
201             value    59.730939  Mises-only
89            liberty    58.520268  Hayek-only
92       institutions    52.109314  Hayek-only
59          evolution    50.058352  Hayek-only
260         socialism    49.533128  Mises-only
383             goods    48.383291  Mises-only
144  entrepreneurship    48.163970  Mises-only
375       cooperation    45.252050  Mises-only
93            process    44.778459  Hayek-only
96         complexity    43.930237  Hayek-only
Section Level — Mises vs Co-cited
                 word    llr_score  dominant_in
136             hayek  1021.689656  Mises+Hayek
213           kirzner   475.216796  Mises+Hayek
31           rothbard   439.455901  Mises+Hayek
298             mises   254.179289   Mises-only
385          lachmann   140.758830  Mises+Hayek
61            boettke    93.976391  Mises+Hayek
10         schumpeter    87.458579  Mises+Hayek
314            menger    86.953284  Mises+Hayek
389             goods    85.340650   Mises-only
387          austrian    84.890369  Mises+Hayek
234          garrison    84.052935  Mises+Hayek
371            action    59.302365   Mises-only
17           buchanan    56.703565  Mises+Hayek
147  entrepreneurship    52.368439  Mises+Hayek
235            lavoie    49.494712  Mises+Hayek
21              labor    48.143219   Mises-only
97              money    46.942005   Mises-only
161        production    39.823535   Mises-only
0           discovery    38.371353  Mises+Hayek
277             rizzo    34.003171  Mises+Hayek
266         socialism    31.929855   Mises-only
106            leeson    29.254606  Mises+Hayek
51             prices    27.204468   Mises-only
243    disequilibrium    26.290291  Mises+Hayek
240              land    25.488689   Mises-only
211             value    24.896673   Mises-only
55            capital    24.770369   Mises-only
196        employment    23.421141   Mises-only
302          exchange    22.384199   Mises-only
151       calculation    22.054291   Mises-only
Section Level — Hayek vs Co-cited
                 word    llr_score  dominant_in
309             mises  4668.750490  Mises+Hayek
139             hayek  3274.480246   Hayek-only
35           rothbard   490.853995  Mises+Hayek
212           kirzner   417.588686  Mises+Hayek
190         knowledge   380.076708   Hayek-only
246             rules   212.282003   Hayek-only
149  entrepreneurship   164.808827  Mises+Hayek
397          austrian   139.078851  Mises+Hayek
382            action   125.154969  Mises+Hayek
394          lachmann   113.653058  Mises+Hayek
141        praxeology   106.991718  Mises+Hayek
283       competition   104.755653   Hayek-only
69            boettke    97.975466  Mises+Hayek
97       entrepreneur    96.272776  Mises+Hayek
188     individualism    74.497997   Hayek-only
12         schumpeter    64.854037  Mises+Hayek
165             weber    64.757096  Mises+Hayek
236            lavoie    61.713237  Mises+Hayek
7      classification    61.444471   Hayek-only
385       uncertainty    58.704492  Mises+Hayek
325               law    55.222740   Hayek-only
248       information    54.404382   Hayek-only
89            liberty    48.369672   Hayek-only
324            menger    44.368804  Mises+Hayek
93       institutions    39.183390   Hayek-only
235          garrison    35.719675  Mises+Hayek
375            eucken    35.276552   Hayek-only
297      coordination    33.038559   Hayek-only
152       calculation    32.472787  Mises+Hayek
67             orders    30.543827   Hayek-only