In [13]:
import pandas as pd

mises_citations_df = pd.read_csv("../data/processed/mises_citations.csv")
hayek_citations_df = pd.read_csv("../data/processed/hayek_citations.csv")
citations_df = pd.read_csv("../data/processed/citations.csv")

In [14]:
hayek_citations_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6281 entries, 0 to 6280
Data columns (total 21 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Unnamed: 0            6281 non-null   int64
 1   paper_id              6281 non-null   int64
 2   raw                   6281 non-null   object
 3   context               6281 non-null   object
 4   co_cited_count        6281 non-null   int64
 5   section_id            6133 non-null   object
 6   paragraph_id          6281 non-null   object
 7   sentence_id           6281 non-null   object
 8   sentence_seq_number   6281 non-null   int64
 9   reference_seq_number  6281 non-null   int64
 10  author                6281 non-null   object
 11  page                  3124 non-null   float64
 12  year                  5768 non-null   float64
 13  title                 6281 non-null   object
 14  filename              6281 non-null   object
 15  sentence_count        6281 non-null   int64
 16  reference_count       6281 non-null   int64
 17  source title          5882 non-null   object
 18  similarity            6281 non-null   float64
 19  keywords              6281 non-null   object
 20  book                  6281 non-null   object
dtypes: float64(3), int64(7), object(11)
memory usage: 1.0+ MB

In [15]:
import pandas as pd

def build_table(mises_df, hayek_df, citations_df, unit_col):
    
    # Conjuntos principais
    mises_set = set(mises_df[unit_col].dropna().unique())
    hayek_set = set(hayek_df[unit_col].dropna().unique())
    
    full_set = set(citations_df[unit_col].dropna().unique())
    
    # Outros autores (exclui Mises e Hayek)
    others_df = citations_df[
        ~citations_df['author'].isin(['Mises', 'Hayek'])
    ]
    others_set = set(others_df[unit_col].dropna().unique())
    
    # Complementos
    not_mises = full_set - mises_set
    not_hayek = full_set - hayek_set
    
    # Função auxiliar segura
    def safe_div(num, den):
        return num / den if den > 0 else 0
    
    # Probabilidades condicionais
    results = {
        'P(Hayek | Mises)': safe_div(len(mises_set & hayek_set), len(mises_set)),
        'P(Mises | Hayek)': safe_div(len(mises_set & hayek_set), len(hayek_set)),
        
        'P(Outros | Mises)': safe_div(len(mises_set & others_set), len(mises_set)),
        'P(Outros | Hayek)': safe_div(len(hayek_set & others_set), len(hayek_set)),
        
        'P(Mises | Outros)': safe_div(len(mises_set & others_set), len(others_set)),
        'P(Hayek | Outros)': safe_div(len(hayek_set & others_set), len(others_set)),
        
        'P(Hayek | ¬Mises)': safe_div(len(hayek_set & not_mises), len(not_mises)),
        'P(Mises | ¬Hayek)': safe_div(len(mises_set & not_hayek), len(not_hayek)),
        
        'P(Outros | ¬Mises)': safe_div(len(others_set & not_mises), len(not_mises)),
        'P(Outros | ¬Hayek)': safe_div(len(others_set & not_hayek), len(not_hayek)),
    }
    
    table = pd.DataFrame({
        'Probabilidade': list(results.keys()),
        'Valor': list(results.values())
    })
    
    # 🔥 Ordena da maior para a menor
    table = table.sort_values(by='Valor', ascending=False).reset_index(drop=True)
    
    return table

In [16]:
sentence_table = build_table(
    mises_citations_df,
    hayek_citations_df,
    citations_df,
    'sentence_id'
)

print('Sentence-level probabilities')
sentence_table

Sentence-level probabilities

        Probabilidade     Valor
0  P(Outros | ¬Mises)  0.976515
1  P(Outros | ¬Hayek)  0.970488
2   P(Outros | Hayek)  0.263824
3   P(Outros | Mises)  0.253837
4    P(Mises | Hayek)  0.095833
5    P(Hayek | Mises)  0.077529
6   P(Mises | ¬Hayek)  0.038051
7   P(Hayek | ¬Mises)  0.030412
8   P(Mises | Outros)  0.010692
9   P(Hayek | Outros)  0.008990

In [17]:
paragraph_table = build_table(
    mises_citations_df,
    hayek_citations_df,
    citations_df,
    'paragraph_id'
)

print('Paragraph-level probabilities')
paragraph_table

Paragraph-level probabilities

        Probabilidade     Valor
0  P(Outros | ¬Mises)  0.982882
1  P(Outros | ¬Hayek)  0.977834
2   P(Outros | Hayek)  0.643593
3   P(Outros | Mises)  0.630948
4    P(Mises | Hayek)  0.193449
5    P(Hayek | Mises)  0.156240
6   P(Mises | ¬Hayek)  0.054670
7   P(Hayek | ¬Mises)  0.042740
8   P(Mises | Outros)  0.040416
9   P(Hayek | Outros)  0.033296

In [18]:
section_table = build_table(
    mises_citations_df,
    hayek_citations_df,
    citations_df,
    'section_id'
)

print('Section-level probabilities')
section_table

Section-level probabilities

        Probabilidade     Valor
0  P(Outros | ¬Mises)  0.995442
1  P(Outros | ¬Hayek)  0.993387
2   P(Outros | Hayek)  0.956155
3   P(Outros | Mises)  0.949568
4    P(Mises | Hayek)  0.442496
5    P(Hayek | Mises)  0.365561
6   P(Mises | Outros)  0.130480
7   P(Hayek | Outros)  0.108542
8   P(Mises | ¬Hayek)  0.097146
9   P(Hayek | ¬Mises)  0.072452

In [19]:
paper_table = build_table(
    mises_citations_df,
    hayek_citations_df,
    citations_df,
    'paper_id'
)

print('Paper-level probabilities')
paper_table

Paper-level probabilities

        Probabilidade     Valor
0   P(Outros | Mises)  1.000000
1   P(Outros | Hayek)  1.000000
2  P(Outros | ¬Mises)  1.000000
3  P(Outros | ¬Hayek)  1.000000
4    P(Mises | Hayek)  0.874903
5   P(Mises | Outros)  0.696557
6    P(Hayek | Mises)  0.615426
7   P(Mises | ¬Hayek)  0.525223
8   P(Hayek | Outros)  0.489974
9   P(Hayek | ¬Mises)  0.201995

Análise de Keywords

In [28]:
import pandas as pd
import numpy as np

def prepare_keywords(df):
    df = df.copy()
    
    # Se keywords for string separada por vírgula
    if isinstance(df["keywords"].iloc[0], str):
        df["keywords"] = df["keywords"].str.split(",")
    
    # Remove espaços extras
    df["keywords"] = df["keywords"].apply(
        lambda lst: [k.strip() for k in lst] if isinstance(lst, list) else []
    )
    
    return df.explode("keywords")

# --- Preparação ---
mises = prepare_keywords(mises_citations_df)
hayek = prepare_keywords(hayek_citations_df)

mises["author"] = "Mises"
hayek["author"] = "Hayek"

df = pd.concat([mises, hayek], ignore_index=True)

# --- Contagem por keyword e autor ---
counts = (
    df.groupby(["keywords", "author"])
      .size()
      .unstack(fill_value=0)
)

# Garantir colunas
for col in ["Mises", "Hayek"]:
    if col not in counts.columns:
        counts[col] = 0

counts["total"] = counts["Mises"] + counts["Hayek"]

# --- Probabilidades marginais ---
counts["P(Mises)"] = counts["Mises"] / counts["total"]
counts["P(Hayek)"] = counts["Hayek"] / counts["total"]

# --- Probabilidade conjunta (assumindo independência) ---
counts["P(Mises and Hayek)"] = (
    counts["P(Mises)"] * counts["P(Hayek)"]
)

# --- Probabilidades exclusivas ---
counts["P(Mises only)"] = (
    counts["P(Mises)"] - counts["P(Mises and Hayek)"]
)

counts["P(Hayek only)"] = (
    counts["P(Hayek)"] - counts["P(Mises and Hayek)"]
)

# --- Tabela final ---
keyword_table = (
    counts[
        [
            "P(Mises)",
            "P(Hayek)",
            "P(Mises and Hayek)",
            "P(Mises only)",
            "P(Hayek only)"
        ]
    ]
    .reset_index()
    .rename(columns={"keywords": "keyword"})
    .sort_values("keyword")
)

keyword_table

author,keyword,P(Mises),P(Hayek),P(Mises and Hayek),P(Mises only),P(Hayek only)
0,['innovation'],0.600000,0.400000,0.240000,0.360000,0.160000
1,['knowledge problem'],0.166667,0.833333,0.138889,0.027778,0.694444
2,['praxeology'],0.945338,0.054662,0.051674,0.893663,0.002988
3,[],0.544609,0.455391,0.248010,0.296599,0.207381

Log-Likelihood

In [20]:
import re

# Load allowed keywords once (do this outside tokenize)
keywords_df = pd.read_csv("keywords_austrian_papers.csv")

# Normalize keywords the same way as tokenize does
allowed_keywords = set()

for kws in keywords_df["Author Keywords"].dropna():
    for kw in str(kws).split(";"):  # assuming keywords are separated by ;
        kw = kw.strip().lower()
        kw = re.sub(r'[^a-zA-Z\s]', ' ', kw)
        allowed_keywords.add(kw)

allowed_keywords

{'austrian analysis',
 'legal order',
 'austrian',
 'east asia',
 'public administration',
 'intelligence',
 'interbank clearing',
 'microeconomic principles',
 'political theory',
 'clusters',
 'sims',
 'kirzner',
 'nonprofits',
 'motivation',
 'subjectivity within objectivism',
 'deficits',
 'a priori knowledge',
 'judging',
 'antitrust',
 'marginal efficiency of capital',
 'sclerosis',
 'risk aversion',
 'morgenstern',
 'non ideal theory',
 'mengerian vs walrasian',
 'neo walrasian',
 'policy objectives and coordination',
 'consumption',
 'erich zimmermann',
 'laffer curve',
 'online societies',
 'pure logic of choice',
 'central european history',
 'knut wicksell',
 'sociology',
 'von mises',
 're switching of techniques',
 'central and eastern europe',
 'irving fisher',
 'economic analysis of law',
 'coordination failure',
 'market rationality',
 'maintenance',
 'witness',
 'complexity economics',
 'sargent',
 'history of philosophy',
 'julian simon',
 'transaction costs',
 'political market',
 'gold clauses',
 'subjective v  objective probability',
 'armen alchian',
 'friedrich a  hayek',
 'creative choice',
 'natural disasters',
 'kant',
 'production structure',
 'ottoman and balkans monetary history',
 'state of confidence',
 'discovery',
 'constitutionalism',
 'radical political economy',
 'cycles',
 'social dilemmas',
 'revolution',
 'scientific progress',
 'dualism',
 'interventions',
 'happiness',
 'formal methods',
 'us versus canada',
 'organizational culture',
 'spontaneous orders',
 'sympathetic mind reading',
 'friedrich hayek',
 'topic modeling',
 'subjectivist interpretation',
 'rural land use policy',
 'evolution of government',
 'augusto pinochet',
 'prediction markets',
 'bellagio group',
 'business cycle',
 'austrian program',
 'praxeological method',
 'sylos labini',
 'rationalism',
 'positional good',
 'roger w  garrison',
 'general equilibrium',
 'political catallaxy',
 'cultural theory',
 'water supply',
 'gifts',
 'influence on the profession',
 'lithuania',
 'local knowledge',
 'jacobs',
 'economic fluctuations',
 'memory',
 'hurricane sandy',
 'pure entrepreneurial profit',
 'relevance',
 'justificationism',
 'don quijote',
 'entrepreneurial state',
 'polycentricity',
 'prices',
 'commodity standard',
 'keynesian demand constraint',
 'constitutional perspective',
 'experts',
 'heterogeneous capital',
 'fatal conceit',
 'new york university',
 'the market',
 'j  ',
 'triadic exchange',
 'globalization',
 'language',
 'autonomy of the political',
 'institutions',
 'mont p lerin society',
 'aesthetics',
 'interest rate sensitivity',
 'richard cantillon',
 'red cross',
 'collaborative innovation bloc',
 'fractional reserves',
 'z  ',
 'ppe',
 'lachmann',
 'relational comparison',
 'population growth',
 'democratic republic of the congo',
 'austrian business cycle model',
 'open science',
 'classical economics',
 'mises',
 'f a  hayek',
 'capital based theory',
 'sympathy',
 'ngrams',
 'polycentric institutions',
 'liberal order',
 'interventionism',
 'pirates',
 'deductivism',
 'experimental economics',
 'fiat money',
 'health',
 'michael porter',
 'sports economics',
 'polycentric law',
 'aristotle s thought',
 'don quixote',
 'value',
 'aristocracy',
 'architecture of governance',
 'extreme governance',
 'piet mondrian',
 'centralized mindset',
 'induced malnovation',
 'government spending',
 'plucking model',
 'lax fiscal policy',
 'merger waves',
 'ethics',
 'nobel memorial prize in economic science',
 'royal elections',
 'milton friedman',
 'climate change',
 'value paradigm',
 'ludwig wittgenstein',
 'social structure',
 'salience imbalance',
 'soviet economy',
 'market share',
 'classical economist',
 'prohibition',
 'value freedom',
 'leadership',
 'credit',
 'objectivism',
 'capital theory',
 'exogenous innovation',
 'imperfect knowledge',
 'utility function',
 'bargaining',
 'pre sensory experience',
 'economic forecasts',
 'process vs structure',
 'german subjective value theory',
 'case studies',
 'kiyotaki wright',
 'recovery',
 'altruism',
 'neo mengerianism',
 'saving and investment',
 'individual rights',
 'spinoza',
 'singapore',
 'consistency',
 'risk based capital',
 'mengerian schumpeterian economics',
 'aggregate expenditure',
 'non price coordination',
 'mainstream economics',
 'scientific communities',
 'non market failure',
 'civil society',
 'peter boettke',
 'contestable markets',
 'smart contracts',
 'payment processing',
 'c  s  peirce',
 'minorities',
 'robust',
 'soviet union',
 'inflation',
 'unemployment',
 'military industrial complex',
 'austrian macroeconomics',
 'pretense of knowledge',
 'upper turning point',
 'growth',
 'trust game',
 'empire',
 'quantum brain',
 'corporate culture',
 'mental models',
 'civil religion',
 'class structure',
 'cartesianism',
 'theory and history',
 'power as mass phenomenon',
 'culture and economics',
 'financial panics',
 'ideal types',
 'stage of process',
 'keynes hayek',
 'pattern coordination',
 'stock',
 'corporation',
 'overshooting',
 'herding',
 'panel data',
 'international development',
 'indifference',
 'john rawls',
 'analytic narrative',
 'expectations',
 'catallactics',
 'government intervention',
 'marginalist revolution',
 'hebb',
 'j  m  keynes',
 'beliefs',
 'tocqueville',
 'carbon tax',
 'statistical inference',
 'housing bubble',
 'indifference analysis',
 'socialist systems',
 'pre modern world',
 'cryptocurrency',
 'hicks',
 'orthodox',
 'ordnungstheorie',
 'central banks',
 'maritime industry',
 'prejudice',
 'ludwig erhard',
 'situational logic',
 'chile',
 'taylorian rate',
 'cybersecurity economics',
 'kingdom of poland',
 'circularities',
 'assurance',
 'meade',
 'hayekian triangle',
 'economic plan',
 'sraffian critique of economic theory',
 'check certification',
 'digital platforms',
 'indian economic thought',
 'capital accounting',
 'bank reserves',
 'frederick nymeyer',
 'lax monetary policy',
 'lavoie',
 'simulation theory',
 'positivism',
 'diversity of money',
 'weber hypothesis',
 'brentano',
 'hahn',
 'promiscuity',
 'burczak',
 'macaulay duration',
 'power',
 'social distance',
 'human action',
 'social evolution',
 'interest rate brake',
 'constitutions',
 'sticky consumption',
 'fiduciary media',
 'non monetized ends and means',
 'hayekian socialism',
 'distributive injustice',
 'neutrality of money',
 'productivity',
 'great recession',
 'contraction',
 'instrumentalism',
 'sliced up value chains',
 'post conflict reconstruction',
 'neuroscience',
 'non market activity',
 'public good',
 'contagion',
 'government failure',
 'austrian political economy',
 'growth of government',
 'natural resources',
 ' lost papers  of ludwig von mises',
 'algorithms',
 'r v g  clarke',
 'easterlin paradox',
 'c  ',
 'market socialism',
 'period of production',
 'granovetter',
 'perfect foresight',
 'prediction',
 'customary law',
 'individual choice',
 'containerization',
 'demsetz',
 'state capacity',
 'politics of banking',
 'nobel laureates',
 'subprime crisis',
 'self interest',
 'preferences over estimates',
 'j  kornai',
 'brexit',
 'labor intensity',
 'occupation',
 'low income families',
 'english constitutional history',
 'financial instability',
 'efficiency wages',
 'karl menger              ',
 'property rights',
 'theory of the firm',
 'gary s  becker',
 'interpretive framework',
 'alfred marshall',
 'austrian school',
 'coverture',
 'experimentation',
 'wage cyclicality',
 'liquidity',
 'hayek s challenge',
 'welfare economics',
 'capital structure',
 'bahamas',
 'real business cycle theory',
 'history of the economic thought',
 'new orleans',
 'sraffian theory',
 'israel kirzner',
 'o  ',
 'urban policy',
 'institutional competition',
 'social innovation',
 'mccloskey',
 'price level',
 'methodenstreit',
 'switzerland',
 'paul samuelson',
 'elections',
 'secular growth',
 'transmission channel',
 'political science',
 'side payments',
 'burden if proof',
 'basel accord',
 'disaster',
 'clubs',
 'covenant marriage',
 'knowledge spillovers',
 'industrial revolution',
 'destutt de tracy',
 'm  ',
 'non neutral money',
 'healthcare',
 'income',
 'federalism',
 'discrimination',
 'old believers',
 'self determination',
 'modularity',
 'complexity',
 'causal ambiguity',
 'competition',
 'giffen behaviour',
 'monetary footprint',
 'land use planning',
 'history of the economic ideas',
 'net present value',
 'financial economics',
 'peter alma',
 'interpretive rationality',
 'management',
 'legal titling',
 'computationalism',
 'models of legislators',
 'social economics',
 'focal points',
 'real business cycles',
 'the structure of production',
 'fiduciary duties of investment advisors and broker dealers',
 'israel m  kirzner',
 'pedagogy',
 'behavioral paternalism',
 'liquidation',
 'anti trust',
 'evolution',
 'public reason',
 'interwar vienna',
 'innovation finance',
 'macroeconomic political economy',
 'kaleidics vs  equilibrium',
 'urban',
 'macroeconomic fluctuation',
 'lynching',
 'econometrics',
 'fractional reserve banking',
 'austrian methodology',
 'capital reversal',
 'emergent order',
 'measurement',
 'macroeconomic policy outlook',
 'neo austrian',
 'civic capital',
 'money',
 'suboptimal conditions',
 'exchange rate',
 'alchian',
 'aristotelianism',
 'political legitimacy',
 'eastern europe',
 'school of salamanca',
 'state of rest',
 'sch tz',
 'social network theory',
 'nobel prize',
 'defense brain',
 'emissions tax',
 'sociology of science',
 'scholasticism',
 'hurst exponent',
 'criminal law',
 'equality',
 'experimental epistemology',
 'normative economics',
 'impersonal exchange',
 'hyperinflation',
 'neoclassical framework',
 'marginal utility theory',
 'technological change',
 'romania',
 'demonetization',
 'i  ',
 'social capital',
 'value heterogeneity',
 'incentives',
 'feynman diagrams',
 'economics of superstition',
 'innovation',
 'innovativeness',
 'role of government',
 'demand',
 'scholarly movements',
 'social objects',
 'equilibrium',
 'depression of          ',
 'counterintelligence',
 'public bad',
 'juan mariana',
 'socialist thought',
 'mathematical foundations of economics',
 'folk psychology',
 'quantity theory',
 'p  ',
 'reductionism',
 'racism',
 'cartesian rationalism',
 'capital complementarity',
 'lionel robbins',
 'causal realist tradition',
 'demand for money',
 'hyman minsky',
 'classification',
 'arbitrage',
 'bearer bonds',
 'endogenous money',
 'social democracy',
 'limited government',
 'counterfactual reasoning',
 'economic organization',
 'philip ii',
 'economist',
 'creative industries',
 '    s',
 'human sociality',
 'eucken',
 'labor market',
 'violence',
 'secondary effects of business cycle',
 'entrepreneurship',
 'infeasible action plans',
 'methodological individualism',
 'dispersed knowledge',
 'eudaimonia',
 'economic anthropology',
 'monetary standard',
 'market dynamics',
 'entrepreneurial alertness',
 'monetary inflation',
 'property rights entrepreneurship',
 'i ',
 'boom',
 'insider information',
 'connectionism',
 'dynamics of the mixed economy',
 'regime uncertainty',
 'credit as commanding height',
 'london school of economics',
 'banking',
 'think tanks',
 'special economic zones',
 'thymology',
 'finance',
 'regulatory arbitrage',
 'involuntary unemployment',
 'political process',
 'mineral resources',
 'menger',
 'minimal state',
 'production contracts',
 'economics profession',
 'agency costs',
 'entangled systems of political economy',
 'principal agent',
 'crimea',
 'structure',
 'perspectives',
 'anomalies',
 'agent based modeling',
 'epistemic turn',
 'planning',
 'prisoners  dilemma mythology',
 'accountant',
 'aid',
 'cluster theory',
 'r a theory',
 'equilibrium vs  non equilibrium theory',
 'positive economics',
 'markets',
 'rights',
 'pure time preference theory of interest',
 'precautionary assets',
 'international economic order',
 'non price parameters of goods and services',
 'rules',
 'nested governance',
 'decision making ability',
 'feudal economy',
 'cognitive psychology',
 'land use regulations',
 'gdp growth',
 'network effects',
 'gerald gaus',
 'teleological perspective',
 'social entrepreneurship',
 'indian economic development',
 'vincent ostrom',
 'economics program',
 'nonneutrality of money',
 'central banking policy',
 'checks and balances',
 'generic and operant analysis',
 'financial regulation',
 'hayek s paradox',
 'persecution and toleration',
 'synthetic control',
 'functionalism',
 'macroeconomic turbulence',
 'experimental',
 'winners and losers',
 'pareto efficient',
 'intellectual history',
 'psychologism',
 'money prices',
 'instruments of interpretation',
 'prosperity',
 'weber',
 'quadratic voting',
 'factory system',
 'consumer wants',
 'afghanistan',
 'history of scotland',
 'monetary equilibrium theory',
 'belief',
 'ultimate resource',
 'subject matter',
 'embodied knowledge',
 'orders',
 'chicago boys',
 'constitutional citizenship',
 'financial crises',
 'accelerator',
 'coordination as process',
 'empirical',
 'crisis management',
 'choice theory',
 'deposits',
 'arrow debreu mckenzie model',
 'radical subjectivism',
 'lucas',
 'buchanan',
 'pattern predictions',
 'mercantilism',
 'radner',
 'mainstream heterodoxy',
 'east of eden',
 'growth management',
 'governance',
 'lighthouses',
 'rent policy',
 'james buchanan',
 'free banking',
 'heterogeneous population groups',
 'ideas and institutions',
 'gdp',
 'justice',
 'classical socialism',
 'intertemporal capital substitution',
 'empiricism',
 'praxeology',
 'credibility',
 'r s analysis',
 'interpretive turn',
 'legal centralism',
 'keynes',
 'slovenia',
 'perfect competition',
 'bank s asset structure',
 'time structure of capital',
 'decision making',
 'sweden',
 'walras',
 'poverty',
 'credit cycles',
 'central banking',
 'producers  good',
 'deontology',
 'philosophy and economics',
 'marriage specific human capital',
 'general laws',
 'moral science',
 'humanitarian aid',
 'spontaneous order',
 'realist social theory',
 'agriculture',
 'el mercurio',
 'r d',
 'efficient markets',
 'constructivism',
 'integrated personality structures',
 'non price institutions',
 'price control',
 'heterogeneous agents',
 'term structure of interest rates',
 'friedrich wieser',
 'neoclassical economics',
 'slowdowns',
 'duration',
 'economies',
 'long memory',
 'research',
 'equity returns',
 'impact assessment guidelines',
 'heterodox practices',
 'accounting',
 'scrappage',
 'speculation',
 'akrasia',
 'austrian chicago synthesis',
 'net consumption net investment theory of profits',
 'monetary economics',
 'truthful revelation',
 'indirect taxes',
 'tacit knowledge',
 'sensation',
 'prudence',
 'commercial friendships',
 'ontology',
 'interaction thesis',
 'housing',
 'capital good',
 'new institutional economics',
 'asymmetric information',
 'environmental economics',
 'monetary systems',
 'hurricane katrina',
 'deirdre mccloskey',
 'forced savings',
 'public finance',
 'common law',
 'agency theory',
 'credit and money multipliers',
 'entrepreneurial planning',
 'enactivism',
 'sociality',
 'moral sentiments',
 'post disaster recovery',
 'economic development',
 'cultural evolution',
 'neutral variation',
 'invest',
 'economic growth',
 'use of knowledge',
 'heterodox mainstream',
 'australian school of economics',
 'hume',
 'contractarianism',
 'sticky prices',
 'organized crime',
 'tuism',
 'george selgin',
 'reputational information and technology',
 'intervention',
 'matt ridley',
 'medium of exchange',
 'schools in economic thought',
 'gunnar myrdal',
 'elinor ostrom',
 'cooperation',
 'coproduction',
 'nineteenth century french liberal economic thought',
 'private provision of public goods',
 'free society',
 'regulatory models',
 'replacement',
 'intra industry trade',
 'inequality',
 'phenomenology',
 'export processing zones',
 'superfluous discovery',
 'family policy',
 'insurance',
 'de stijl',
 'classical liberalism',
 'federal reserve',
 'open square',
 'entrepreneurial inspiration',
 'repressed inflation',
 'traveler s tale',
 'argument',
 'liberal peace',
 'principles of economics',
 'action',
 'unit of account',
 'cantillon effects',
 'computers',
 'marginalism',
 'capitalism',
 'hermeneutics',
 'arbitrariness',
 'coherence',
 'art market',
 'barriers to entry',
 'coase',
 'transition economies',
 'self organizing systems',
 'evolutionary game theory',
 'nonprice coordination',
 'richard rorty',
 'analytic narratives',
 'competitive advantage',
 'virtues',
 'fisher effect',
 'james otteson',
 'price controls  centralized mindset',
 'libertarianism',
 'federal reserve policy',
 'blue wall of silence',
 'utilization',
 'interjurisdictional competition',
 'group selection',
 'carl schmitt',
 'utility maximization',
 'f a hayek',
 'monetary expansion',
 'rent creation',
 'civilization',
 'institutional robustness',
 'adam smith',
 'human capital',
 'austrian pfolitical economy',
 'plan disequilibrium',
 'and economics',
 'signal to noise',
 'invisible hand',
 'is lm model',
 'debate',
 'economic evolution',
 'open vs  closed systems',
 'b ',
 'economic value added',
 'urban and regional planning',
 'austrian school of economics  origins of the ',
 'comparative institutional analysis',
 'intrinsic value',
 'crowding out',
 'new urbanism',
 'new austrian',
 'deposit insurance',
 'obsolescence',
 'libertarian marxism',
 'state legitimacy',
 'cognitive network  cognit ',
 'turning point',
 'monetary history',
 'opportunity',
 'oregon',
 'fracking',
 'economic freedom',
 'forensic science',
 'money stream stabilization',
 'adaptation',
 'macro foundations for micro',
 'freedom of entry',
 'sticky information',
 'gudeman',
 'designer drugs',
 'homo economicus',
 'aggregation',
 'liberalism and authority',
 'structure of production',
 'homelessness',
 'free will',
 'depression',
 'immigration',
 'labor markets',
 'time series forecasting',
 'sunk costs',
 'schools of thought',
 'intersubjectivity',
 'free enterprise system',
 'neurath',
 'fundamental analysis',
 'kiznerian entrepreneurship',
 'pandemics',
 'progress',
 'elite theory',
 'royal navy',
 'monetary theory',
 'gary becker',
 'exchange frictions',
 'operators',
 'transitivity',
 'reswitching',
 'production theory',
 'systems theory',
 'degree of roundaboutness',
 'empirical labour theory of value',
 'f  ',
 'the theory of the firm',
 'interpretation',
 'asset price inflation',
 'land',
 'soft budget constraint',
 'great depression',
 'monetary reform',
 'political and economic order',
 'evasion',
 'john stuart mill',
 'consumer behavior',
 'extended order',
 'spontaneous evolution',
 'economic geography',
 'rational expectations',
 'b hm bawerk s theory of capital',
 'laissez faire',
 'theory absorption',
 'wagner s law',
 'comparative economics',
 'honor culture',
 'circular flow model',
 'anti psychologism',
 'cost accounting',
 'equilibrium constructs',
 'savings',
 'theories of the firm',
 'auctions',
 'k   https   www aeaweb org jel guide jel php',
 'volatility',
 'action space',
 'monetary policy',
 'animal spirits',
 'horizontal relationships',
 'q  ',
 'minsky',
 'production based economics',
 'vincent and elinor ostrom',
 'money emergence',
 'panic of     ',
 'benevolence',
 'neopositivism',
 'gift exchange',
 'market competition',
 'price gouging',
 'loanable funds',
 'administrative law',
 'local minima',
 'sterilization',
 'business cycle theory',
 'friedrich von wieser',
 'counterfactuals',
 'contractual nullification',
 'exact laws',
 'complexity theory',
 'life world',
 'institutional evolution',
 'transition',
 'north',
 'hayekian business cycle theory',
 'public choice',
 'intellectuals',
 'economics of the arts',
 'justified true belief',
 'states as orders',
 'ucla tradition',
 'psychology',
 'innovation systems',
 'monetary non neutrality',
 'avant garde',
 'karl popper',
 'financial institutions',
 'history of austrian economics',
 'fiscal policy',
 'relational market obligations',
 'local and community currency',

In [21]:
mises_only_df = mises_citations_df[
    (mises_citations_df['co_cited_count'] == 0)
]

hayek_only_df = hayek_citations_df[
    (hayek_citations_df['co_cited_count'] == 0)
]

mises_hayek_df = mises_citations_df[
    (mises_citations_df['co_cited_count'] > 0)
]


import math
import re
from collections import Counter
import pandas as pd

# -------------------------
# Tokenização simples
# -------------------------
def tokenize(text):
    text = text.lower()
    text = re.sub(r'[^a-zA-Z\s]', ' ', text)

    tokens = text.split()

    return [t for t in tokens if t in allowed_keywords]



# -------------------------
# Agregação por unidade
# -------------------------
def aggregate_text(df, group_col):
    return (
        df.groupby(group_col)['context']
        .apply(lambda x: ' '.join(x))
        .dropna()
    )


# -------------------------
# Construir Counter
# -------------------------
def build_counter(text_series):
    tokens = []
    for text in text_series:
        tokens.extend(tokenize(text))
    return Counter(tokens)


# -------------------------
# LLR binário
# -------------------------
def compute_llr(counter_a, counter_b, label_a, label_b):
    results = []
    
    total_a = sum(counter_a.values())
    total_b = sum(counter_b.values())
    
    vocab = set(counter_a.keys()).union(counter_b.keys())
    
    for word in vocab:
        k1 = counter_a.get(word, 0)
        k2 = counter_b.get(word, 0)
        
        if k1 == 0 and k2 == 0:
            continue
        
        E1 = total_a * (k1 + k2) / (total_a + total_b)
        E2 = total_b * (k1 + k2) / (total_a + total_b)
        
        score = 0
        if k1 > 0:
            score += k1 * math.log(k1 / E1)
        if k2 > 0:
            score += k2 * math.log(k2 / E2)
        
        score *= 2
        
        prop_a = k1 / total_a if total_a > 0 else 0
        prop_b = k2 / total_b if total_b > 0 else 0
        
        dominant = label_a if prop_a > prop_b else label_b
        
        results.append((word, score, dominant))
    
    return pd.DataFrame(results, columns=["word", "llr_score", "dominant_in"])\
             .sort_values("llr_score", ascending=False)


# -------------------------
# Função geral
# -------------------------
def run_pairwise_llr(df_a, df_b, label_a, label_b, group_col):
    
    agg_a = aggregate_text(df_a, group_col)
    agg_b = aggregate_text(df_b, group_col)
    
    counter_a = build_counter(agg_a)
    counter_b = build_counter(agg_b)
    
    return compute_llr(counter_a, counter_b, label_a, label_b)

In [22]:

# ===========================
# 🚀 EXECUÇÃO POR SENTENCE_ID
# ===========================

# 1️⃣ Mises-only vs Hayek-only
llr_mh = run_pairwise_llr(
    mises_only_df,
    hayek_only_df,
    "Mises-only",
    "Hayek-only",
    group_col="sentence_id"
)

# 2️⃣ Mises-only vs Mises+Hayek
llr_mm = run_pairwise_llr(
    mises_only_df,
    mises_hayek_df,
    "Mises-only",
    "Mises+Hayek",
    group_col="sentence_id"
)

# 3️⃣ Hayek-only vs Mises+Hayek
llr_hm = run_pairwise_llr(
    hayek_only_df,
    mises_hayek_df,
    "Hayek-only",
    "Mises+Hayek",
    group_col="sentence_id"
)

print("Mises vs Hayek")
print(llr_mh.head(30))

print("Mises vs Co-cited")
print(llr_mm.head(30))

print("Hayek vs Co-cited")
print(llr_hm.head(30))

Mises vs Hayek
                 word    llr_score dominant_in
100             hayek  8189.771819  Hayek-only
196             mises  7397.727491  Mises-only
168         knowledge   496.862169  Hayek-only
377            action   384.322362  Mises-only
79              rules   319.426399  Hayek-only
190        praxeology   190.579121  Mises-only
357       information   148.655130  Hayek-only
57      individualism   133.530416  Hayek-only
355      entrepreneur   132.734781  Mises-only
198       competition   116.744715  Hayek-only
269       calculation   103.752597  Mises-only
98          discovery   102.809764  Hayek-only
257             money    96.164468  Mises-only
33           exchange    93.783455  Mises-only
342    classification    77.234983  Hayek-only
270       probability    74.474879  Mises-only
324       equilibrium    69.878669  Hayek-only
125             labor    68.792875  Mises-only
320      coordination    67.469981  Hayek-only
293            profit    64.090605  Mises-only
278           liberty    62.583731  Hayek-only
213             value    60.226305  Mises-only
179      institutions    52.207470  Hayek-only
223         evolution    50.132762  Hayek-only
195        complexity    48.421505  Hayek-only
368  entrepreneurship    48.103702  Mises-only
256           process    46.126643  Hayek-only
243             goods    45.617086  Mises-only
329       cooperation    45.191332  Mises-only
319         socialism    44.424221  Mises-only
Mises vs Co-cited
                 word    llr_score  dominant_in
98              hayek  1036.893704  Mises+Hayek
19            kirzner   483.527719  Mises+Hayek
173          rothbard   469.159478  Mises+Hayek
198             mises   263.179346   Mises-only
190          lachmann   142.904902  Mises+Hayek
323           boettke    96.414833  Mises+Hayek
33             menger    89.871896  Mises+Hayek
380          garrison    89.266563  Mises+Hayek
225        schumpeter    89.243881  Mises+Hayek
248             goods    88.987398   Mises-only
8            austrian    87.845258  Mises+Hayek
383            action    62.936820   Mises-only
159          buchanan    56.928405  Mises+Hayek
262             money    54.910897   Mises-only
375  entrepreneurship    52.869416  Mises+Hayek
35             lavoie    49.704863  Mises+Hayek
126             labor    47.785612   Mises-only
241        production    38.841372   Mises-only
96          discovery    38.557503  Mises+Hayek
155             rizzo    35.774530  Mises+Hayek
325         socialism    34.316270   Mises-only
360            leeson    29.346035  Mises+Hayek
165            prices    28.530906   Mises-only
63     disequilibrium    26.400744  Mises+Hayek
216             value    25.705672   Mises-only
133              land    25.355358   Mises-only
114           capital    24.321257   Mises-only
209        employment    24.282409   Mises-only
31           exchange    23.840744   Mises-only
202            keynes    22.846482  Mises+Hayek
Hayek vs Co-cited
                 word    llr_score  dominant_in
204             mises  4683.480007  Mises+Hayek
105             hayek  3321.569631   Hayek-only
180          rothbard   503.611487  Mises+Hayek
21            kirzner   413.759572  Mises+Hayek
175         knowledge   383.305595   Hayek-only
82              rules   214.581999   Hayek-only
384  entrepreneurship   165.337320  Mises+Hayek
9            austrian   140.880487  Mises+Hayek
394            action   123.032325  Mises+Hayek
197          lachmann   115.362804  Mises+Hayek
200        praxeology   112.629715  Mises+Hayek
205       competition   106.094433   Hayek-only
332           boettke   104.032825  Mises+Hayek
372      entrepreneur    96.660873  Mises+Hayek
59      individualism    74.138076   Hayek-only
230        schumpeter    66.215878  Mises+Hayek
124             weber    65.007812  Mises+Hayek
41             lavoie    61.871065  Mises+Hayek
360    classification    61.231290   Hayek-only
397       uncertainty    59.033507  Mises+Hayek
2                 law    54.862204   Hayek-only
375       information    54.791341   Hayek-only
292           liberty    51.414472   Hayek-only
39             menger    46.287060  Mises+Hayek
187      institutions    38.904640   Hayek-only
390          garrison    37.031716  Mises+Hayek
336      coordination    32.869272   Hayek-only
148            orders    31.409968   Hayek-only
55          selection    30.177515   Hayek-only
109          coercion    30.177515   Hayek-only

In [23]:
# ==========================
# 🔥 EXECUÇÃO POR PARAGRAPH_ID
# ==========================

# 1️⃣ Mises-only vs Hayek-only
llr_mh_paragraph = run_pairwise_llr(
    mises_only_df,
    hayek_only_df,
    "Mises-only",
    "Hayek-only",
    group_col="paragraph_id"
)

# 2️⃣ Mises-only vs Mises+Hayek
llr_mm_paragraph = run_pairwise_llr(
    mises_only_df,
    mises_hayek_df,
    "Mises-only",
    "Mises+Hayek",
    group_col="paragraph_id"
)

# 3️⃣ Hayek-only vs Mises+Hayek
llr_hm_paragraph = run_pairwise_llr(
    hayek_only_df,
    mises_hayek_df,
    "Hayek-only",
    "Mises+Hayek",
    group_col="paragraph_id"
)


print("Paragraph Level — Mises vs Hayek")
print(llr_mh_paragraph.head(30))

print("Paragraph Level — Mises vs Co-cited")
print(llr_mm_paragraph.head(30))

print("Paragraph Level — Hayek vs Co-cited")
print(llr_hm_paragraph.head(30))

Paragraph Level — Mises vs Hayek
                 word    llr_score dominant_in
100             hayek  8189.771819  Hayek-only
196             mises  7397.727491  Mises-only
168         knowledge   496.862169  Hayek-only
377            action   384.322362  Mises-only
79              rules   319.426399  Hayek-only
190        praxeology   190.579121  Mises-only
357       information   148.655130  Hayek-only
57      individualism   133.530416  Hayek-only
355      entrepreneur   132.734781  Mises-only
198       competition   116.744715  Hayek-only
269       calculation   103.752597  Mises-only
98          discovery   102.809764  Hayek-only
257             money    96.164468  Mises-only
33           exchange    93.783455  Mises-only
342    classification    77.234983  Hayek-only
270       probability    74.474879  Mises-only
324       equilibrium    69.878669  Hayek-only
125             labor    68.792875  Mises-only
320      coordination    67.469981  Hayek-only
293            profit    64.090605  Mises-only
278           liberty    62.583731  Hayek-only
213             value    60.226305  Mises-only
179      institutions    52.207470  Hayek-only
223         evolution    50.132762  Hayek-only
195        complexity    48.421505  Hayek-only
368  entrepreneurship    48.103702  Mises-only
256           process    46.126643  Hayek-only
243             goods    45.617086  Mises-only
329       cooperation    45.191332  Mises-only
319         socialism    44.424221  Mises-only
Paragraph Level — Mises vs Co-cited
                 word    llr_score  dominant_in
98              hayek  1036.893704  Mises+Hayek
19            kirzner   483.527719  Mises+Hayek
173          rothbard   469.159478  Mises+Hayek
198             mises   263.179346   Mises-only
190          lachmann   142.904902  Mises+Hayek
323           boettke    96.414833  Mises+Hayek
33             menger    89.871896  Mises+Hayek
380          garrison    89.266563  Mises+Hayek
225        schumpeter    89.243881  Mises+Hayek
248             goods    88.987398   Mises-only
8            austrian    87.845258  Mises+Hayek
383            action    62.936820   Mises-only
160          buchanan    56.928405  Mises+Hayek
262             money    54.910897   Mises-only
375  entrepreneurship    52.869416  Mises+Hayek
35             lavoie    49.704863  Mises+Hayek
126             labor    47.785612   Mises-only
241        production    38.841372   Mises-only
96          discovery    38.557503  Mises+Hayek
155             rizzo    35.774530  Mises+Hayek
325         socialism    34.316270   Mises-only
360            leeson    29.346035  Mises+Hayek
165            prices    28.530906   Mises-only
63     disequilibrium    26.400744  Mises+Hayek
216             value    25.705672   Mises-only
133              land    25.355358   Mises-only
114           capital    24.321257   Mises-only
209        employment    24.282409   Mises-only
31           exchange    23.840744   Mises-only
202            keynes    22.846482  Mises+Hayek
Paragraph Level — Hayek vs Co-cited
                 word    llr_score  dominant_in
204             mises  4683.480007  Mises+Hayek
105             hayek  3321.569631   Hayek-only
180          rothbard   503.611487  Mises+Hayek
21            kirzner   413.759572  Mises+Hayek
175         knowledge   383.305595   Hayek-only
82              rules   214.581999   Hayek-only
384  entrepreneurship   165.337320  Mises+Hayek
9            austrian   140.880487  Mises+Hayek
395            action   123.032325  Mises+Hayek
197          lachmann   115.362804  Mises+Hayek
200        praxeology   112.629715  Mises+Hayek
205       competition   106.094433   Hayek-only
332           boettke   104.032825  Mises+Hayek
372      entrepreneur    96.660873  Mises+Hayek
59      individualism    74.138076   Hayek-only
230        schumpeter    66.215878  Mises+Hayek
124             weber    65.007812  Mises+Hayek
41             lavoie    61.871065  Mises+Hayek
360    classification    61.231290   Hayek-only
397       uncertainty    59.033507  Mises+Hayek
2                 law    54.862204   Hayek-only
375       information    54.791341   Hayek-only
292           liberty    51.414472   Hayek-only
39             menger    46.287060  Mises+Hayek
187      institutions    38.904640   Hayek-only
390          garrison    37.031716  Mises+Hayek
336      coordination    32.869272   Hayek-only
148            orders    31.409968   Hayek-only
55          selection    30.177515   Hayek-only
109          coercion    30.177515   Hayek-only

In [24]:
# ==========================
# 🔥 EXECUÇÃO POR SECTION_ID
# ==========================

# 1️⃣ Mises-only vs Hayek-only
llr_mh_section = run_pairwise_llr(
    mises_only_df,
    hayek_only_df,
    "Mises-only",
    "Hayek-only",
    group_col="section_id"
)

# 2️⃣ Mises-only vs Mises+Hayek
llr_mm_section = run_pairwise_llr(
    mises_only_df,
    mises_hayek_df,
    "Mises-only",
    "Mises+Hayek",
    group_col="section_id"
)

# 3️⃣ Hayek-only vs Mises+Hayek
llr_hm_section = run_pairwise_llr(
    hayek_only_df,
    mises_hayek_df,
    "Hayek-only",
    "Mises+Hayek",
    group_col="section_id"
)


print("Section Level — Mises vs Hayek")
print(llr_mh_section.head(30))

print("Section Level — Mises vs Co-cited")
print(llr_mm_section.head(30))

print("Section Level — Hayek vs Co-cited")
print(llr_hm_section.head(30))

Section Level — Mises vs Hayek
                 word    llr_score dominant_in
100             hayek  8049.470382  Hayek-only
196             mises  7316.909454  Mises-only
168         knowledge   492.693281  Hayek-only
377            action   378.307505  Mises-only
79              rules   314.834572  Hayek-only
190        praxeology   186.418239  Mises-only
357       information   147.148716  Hayek-only
57      individualism   144.414398  Hayek-only
355      entrepreneur   127.870088  Mises-only
198       competition   121.548361  Hayek-only
269       calculation   113.592284  Mises-only
98          discovery   102.714905  Hayek-only
33           exchange    90.417125  Mises-only
257             money    84.553712  Mises-only
342    classification    77.162551  Hayek-only
270       probability    74.561824  Mises-only
324       equilibrium    72.528935  Hayek-only
125             labor    68.886496  Mises-only
320      coordination    67.403149  Hayek-only
293            profit    64.177968  Mises-only
213             value    59.730939  Mises-only
278           liberty    58.520268  Hayek-only
179      institutions    52.109314  Hayek-only
223         evolution    50.058352  Hayek-only
319         socialism    49.533128  Mises-only
243             goods    48.383291  Mises-only
368  entrepreneurship    48.163970  Mises-only
329       cooperation    45.252050  Mises-only
256           process    44.778459  Hayek-only
195        complexity    43.930237  Hayek-only
Section Level — Mises vs Co-cited
                 word    llr_score  dominant_in
98              hayek  1021.689656  Mises+Hayek
19            kirzner   475.216796  Mises+Hayek
173          rothbard   439.455901  Mises+Hayek
198             mises   254.179289   Mises-only
190          lachmann   140.758830  Mises+Hayek
324           boettke    93.976391  Mises+Hayek
225        schumpeter    87.458579  Mises+Hayek
33             menger    86.953284  Mises+Hayek
249             goods    85.340650   Mises-only
8            austrian    84.890369  Mises+Hayek
380          garrison    84.052935  Mises+Hayek
383            action    59.302365   Mises-only
159          buchanan    56.703565  Mises+Hayek
375  entrepreneurship    52.368439  Mises+Hayek
35             lavoie    49.494712  Mises+Hayek
126             labor    48.143219   Mises-only
263             money    46.942005   Mises-only
242        production    39.823535   Mises-only
96          discovery    38.371353  Mises+Hayek
155             rizzo    34.003171  Mises+Hayek
326         socialism    31.929855   Mises-only
361            leeson    29.254606  Mises+Hayek
165            prices    27.204468   Mises-only
63     disequilibrium    26.290291  Mises+Hayek
133              land    25.488689   Mises-only
216             value    24.896673   Mises-only
114           capital    24.770369   Mises-only
209        employment    23.421141   Mises-only
31           exchange    22.384199   Mises-only
277       calculation    22.054291   Mises-only
Section Level — Hayek vs Co-cited
                 word    llr_score  dominant_in
204             mises  4668.750490  Mises+Hayek
105             hayek  3274.480246   Hayek-only
180          rothbard   490.853995  Mises+Hayek
21            kirzner   417.588686  Mises+Hayek
175         knowledge   380.076708   Hayek-only
82              rules   212.282003   Hayek-only
384  entrepreneurship   164.808827  Mises+Hayek
9            austrian   139.078851  Mises+Hayek
395            action   125.154969  Mises+Hayek
197          lachmann   113.653058  Mises+Hayek
200        praxeology   106.991718  Mises+Hayek
205       competition   104.755653   Hayek-only
332           boettke    97.975466  Mises+Hayek
372      entrepreneur    96.272776  Mises+Hayek
59      individualism    74.497997   Hayek-only
230        schumpeter    64.854037  Mises+Hayek
124             weber    64.757096  Mises+Hayek
41             lavoie    61.713237  Mises+Hayek
360    classification    61.444471   Hayek-only
397       uncertainty    58.704492  Mises+Hayek
2                 law    55.222740   Hayek-only
375       information    54.404382   Hayek-only
292           liberty    48.369672   Hayek-only
39             menger    44.368804  Mises+Hayek
187      institutions    39.183390   Hayek-only
390          garrison    35.719675  Mises+Hayek
379            eucken    35.276552   Hayek-only
336      coordination    33.038559   Hayek-only
283       calculation    32.472787  Mises+Hayek
148            orders    30.543827   Hayek-only